[package]
name = "randoku"
version = "0.1.0"
authors = ["Christian Stefanescu <christian.stefanescu@lawpilots.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { git = "https://github.com/djc/askama", default-features = false, features=["with-rocket"]}
askama_rocket = { version = "0.11.0-rc.1" }
rand = { version = "0.8", features=["std", "std_rng"]}
lazy_static = "1.4"
rocket = { version = "0.5.0-rc.1", default-features = false }
